---
title: "Untitled"
output: html_document
---
	
```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```


```{r echo = FALSE}
library(devtools)
load_all("../../tmaptools")
load_all("../")
library(raster)
library(sf)
library(spData)
ohio = subset(us_states, NAME == "Ohio")
raster_template = raster(extent(ohio), resolution = 0.5,
						 crs = st_crs(ohio)$proj4string)

##
ohio_raster = rasterize(as(ohio, "Spatial"), raster_template)

ohio_raster2 <- ohio_raster
names(ohio_raster2@data@attributes[[1]])[4:7] <- paste0(names(ohio_raster2@data@attributes[[1]])[4:7], "_2")

##
ohio_stack <- stack(ohio_raster, ohio_raster2)

##
ohio_brick <- brick(ohio_raster, ohio_raster2)


##
data(land)

##
land_cover <- raster(land, layer=1)

##
land_trees <- raster(land, layer=3)

##
land_stack <- as(land, "RasterStack")

##
if (file.exists("osm_nld.rdata")) {
	load(file = "osm_nld.rdata")	
} else {
	data(NLD_muni)
	osm <- read_osm(NLD_muni, ext=1.2)
	save(osm, file = "osm_nld.rdata")
}

if (file.exists(c("raster_tifs.rdata", "TerraColor_SanFrancisco_US_15m.tif"))) {
	load("raster_tifs.rdata")
	SFbdisk <- brick("TerraColor_SanFrancisco_US_15m.tif")
	SFsdisk <- stack("TerraColor_SanFrancisco_US_15m.tif")
} else {
	tmpfile <- tempfile(fileext = "zip")
	tmpdir <- tempdir()
	download.file("http://www.terracolor.net/download/tc_sanfrancisco_us_geotiff.zip", destfile = tmpfile)
	unzip(tmpfile, exdir = ".")
	list.files(tmpdir)
	
	SFbdisk <- brick("TerraColor_SanFrancisco_US_15m.tif")
	SFsdisk <- stack("TerraColor_SanFrancisco_US_15m.tif")
	
	##
	SFb <- aggregate(SFbdisk, fact = 8)
	
	##
	SFs <- aggregate(SFsdisk, fact = 8)
	save(SFb, SFs, file = "raster_tifs.rdata")
}


rlist <- list(
	ohio_raster = ohio_raster,
	ohio_stack = ohio_stack,
	ohio_brick = ohio_brick,
	land = land,
	land_cover = land_cover,
	land_trees = land_trees,
	land_stack = land_stack,
	osm = osm,
	SFb = SFb,
	SFs = SFs
	# SFbdisk = SFbdisk,
	# SFsdisk = SFsdisk
)
```

## Test get_raster_data

```{r}
for (i in 1:length(rlist)) {
	rl <- rlist[[i]]
	nm <- names(rlist)[i]
	
	cat("------------------------------\n")
	cat("--------------", nm, "----------------\n")
	cat("------------------------------\n")
	#print(str(rl))
	cat("------------------------------\n")
	str(get_raster_data(rl))
}
```

## Plot get_raster_data

```{r}
for (i in 1:length(rlist)) {
	rl <- rlist[[i]]
	nm <- names(rlist)[i]
	
	cat("------------------------------\n")
	cat("--------------", nm, "----------------\n")
	cat("------------------------------\n")
	print(qtm(rl))
	cat("------------------------------\n")
}
```

## Test
