---
title: "tmap v4: a sneak peek"
author: "Martijn Tennekes"
date: "`r Sys.Date()`"
output: 
  html_document:
    toc: true
    toc_float:
      collapsed: false
      smooth_scroll: false
    toc_depth: 2
link-citations: yes
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```


## tmap v4: almost completely new

```r
data(World)
tm_shape(World) +
tm_polygons("HPI", fill.scale = tm_scale_intervals)

```

The next major update of tmap will be a massive one. Although tmap is a well-known and greatly appreciated package in the r-spatial world, there are a couple of bottlenecks which make it difficult to maintain and extend. The upcoming tmap v4 will overcome these shortcomings. It is still in development, but now is a good time for a sneak peek.










## Why?

Although tmap 


The upcoming tmap version 4.0 will be totally different

There are two major bottlenecks in tmap v3: it is hard to extend and the layer functions (especially `tm_symbols`) contain too many arguments to see the trees through the forest.


* _Extendibility_: we got a lot of questions via StackOverflow and GitHub such as: "Is it possible to map a data variable to line type?" and "Is it possible to create a bivariate choropleth?". Many of those feature request where hard to implement because the layer functions and its arguments were partly hard-coded in tmap. As of v4, the layer function definitions as not part of the core of tmap anymore, which makes it easy to improve and add layer functions. The main layer functions such as `tm_polygons` and `tm_symbols` will still be part of the `tmap` package, but potential new layer functions, such as `tm_cartogram`, `tm_doughnuts`, and `tm_flows`, will probably be part of add-on packages.

* _Too many arguments_: Some layer functions, especially `tm_symbols`, have so many arguments that it is hard to see the trees through the forest. As of v4, the layer function arguments will be neatly organized. Each aesthetic will only have 4 arguments:

    1. a 'main' argument (e.g. `"col"`) that determines which value or data variable to use. This is similar to the current tmap version.
    2. a 'scale' argument (e.g. `"col.scale"`) which determines _how_ the data variables are mapped to (in this case) a color palette. For each type of scale there will be a function (`tm_scale_categorical`, `tm_scale_oridnal` `tm_scale_discrete`, `tm_scale_intervals`, and `tm_scale_continuous` will be the main ones) that contains the arguments that setup the scale.
    3. a 'legend' arugment (e.g. `"col.legend"`) which determines what type of legend will be shown and where. The position of the legends has been changed as well and is much more flexible, especially regarding outside positioning.
    4. a 'free' arugment (e.g. `"col.free"`) which determines whether scale are shared across facets. It will also be possible to set this per facet dimension (row, column, and page).









## Layer functions




### More and more aethetics

### Its arguments: scale, and free, legend

### _transformation_ and _mapping_ aesthetics

### Extendable



## Scales




## Graphics

### Legend placement

### Extendable

## Spatial classes

### Native support for sf, stars and terra

### Extendable
