sudo apt-get install libgdal-dev 
sudo apt-get install libgeos-dev 
sudo apt-get install libproj-dev 
sudo apt-get install libudunits2-dev 
sudo apt-get install libv8-dev 
sudo apt-get install libjq-dev 
sudo apt-get install libprotobuf-dev 
sudo apt-get install protobuf-compiler
sudo apt-get install libssl-dev
sudo apt-get install libcairo2-dev
