---
title: "tmap advanced: grouping of components"
output: 
  bookdown::html_vignette2:
pkgdown:
  as_is: true
template:
  math-rendering: mathjax
bibliography: '`r system.file("tmap.bib", package="tmap")`'
csl: "`r system.file('ieee.csl', package = 'tmap')`"
editor_options: 
  chunk_output_type: console
---

```{r, include = FALSE}
knitr::opts_chunk$set(
  collapse = TRUE,
  out.width = "100%",
  dpi = 300,
  fig.width = 7.2916667,
  comment = "#>"
)
hook_output <- knitr::knit_hooks$get("output")
knitr::knit_hooks$set(output = function(x, options) {
   lines <- options$output.lines
   if (is.null(lines)) {
     return(hook_output(x, options))  # pass to default hook
   }
   x <- unlist(strsplit(x, "\n"))
   more <- "..."
   if (length(lines)==1) {        # first n lines
     if (length(x) > lines) {
       # truncate the output, but add ....
       x <- c(head(x, lines), more)
     }
   } else {
     x <- c(more, x[lines], more)
   }
   # paste these lines together
   x <- paste(c(x, ""), collapse = "\n")
   hook_output(x, options)
 })

```


```{r, echo = FALSE, message = FALSE}
library(tmap)
tmap_options(scale = 0.75)
```

When component share the same position (see [vignette about positions](https://r-tmap.github.io/tmap/articles/41_position)), we can specify how they are grouped via `tm_comp_group()`.

We will use a self-made map component, made with the grid package that we show via `tm_inset()`.
```{r, fig.height = 6}
g = function(text) grid::gList(
  grid::rectGrob(gp=grid::gpar(fill = "gold")), 
  grid::circleGrob(r = .45), 
  grid::textGrob(text))
b = function(text) grid::gList(
  grid::rectGrob(gp=grid::gpar(fill = "steelblue")), 
  grid::circleGrob(r = .45), 
  grid::textGrob(text))
```


# Grouped components

```{r, fig.height = 6}
tm = tm_shape(NLD_muni) +
	tm_polygons("grey95", col = "grey90") +
	tm_inset(g("A1"), group_id = "A") +
	tm_inset(g("A2"), group_id = "A") +
	tm_inset(g("A3"), group_id = "A") +
	tm_layout(asp = 1)

tm + tm_comp_group("A", position = tm_pos_in("left", "top"))
```
